const supabaseClient = window.supabase.createClient('https://scdgdfxkvkgqueeozznd.supabase.co', 'sb_publishable_UgQh8Fq2C-ydgDCPSbii6A_J5Eqoia1');
const sampleTournaments=[{id:'copa',day:'21',month:'AGO',year:'2026',title:'Copa Miramarense · 5ª Edición',status:'Inscripciones abiertas',location:'Club Náutico Miramar',price:'$30.000 por persona',categories:'5ª y 6ª Femenino',date:'21/08 - 23/08',contact:'5492233122044',pairs:['Carolina Rossi / Mariela Gómez','Sofía Martínez / Luciana Díaz','Valeria Fernández / Andrea Ruiz']},{id:'primavera',day:'19',month:'SEP',year:'2026',title:'Abierto de Primavera',status:'Próximamente',location:'Complejo La Cancha',price:'A confirmar',categories:'Categorías mixtas',date:'19/09 - 20/09',contact:'5492233122044',pairs:[]}];
let tournaments=sampleTournaments;
const formatCardDate=value=>{const [year,month,day]=String(value||'').split('-');return month&&day?`${day}/${month}`:''};
const list=document.querySelector('#tournament-list'),dialog=document.querySelector('#tournament-dialog'),pages=document.querySelector('#detail-pages');
dialog.addEventListener('toggle',()=>document.body.classList.toggle('modal-open',dialog.open));
const tournamentGroup=t=>t.status==='En curso'?'current':t.status==='Finalizado'?'finished':'upcoming';
const tournamentCard=t=>{const group=tournamentGroup(t);const statusClass=group==='current'?'card-status--current':group==='finished'?'card-status--finished':'card-status--open';return `<article class="tournament-card tournament-card--${group}"><button type="button" data-id="${t.id}" aria-label="Ver torneo: ${t.title}"><span class="tournament-card__top"><strong>${t.title} (${t.categories})</strong><span class="card-status ${statusClass}">${group==='upcoming'?'Abierto':group==='finished'?'Finalizado':'En curso'}</span></span><span class="tournament-card__meta">${t.location} · ${t.date.replace(' - ', ' al ')}</span></button></article>`};
const tournamentSection=(title,items)=>!items.length?'':`<section class="tournament-home-section"><h3>${title}</h3><div class="tournament-home-section__list">${items.map(tournamentCard).join('')}</div></section>`;
const renderTournamentList=()=>{const current=tournaments.filter(t=>tournamentGroup(t)==='current'),upcoming=tournaments.filter(t=>tournamentGroup(t)==='upcoming'),finished=tournaments.filter(t=>tournamentGroup(t)==='finished');list.innerHTML=`${tournamentSection('En curso',current)}${tournamentSection('Próximos torneos',upcoming)}${tournamentSection('Terminados',finished)}`||'<p class="tournament-list__empty">No hay torneos publicados por el momento.</p>'};
renderTournamentList();
list.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;const t=tournaments.find(x=>x.id===b.dataset.id);const dialogTitle=document.querySelector('#dialog-title');delete dialogTitle.dataset.baseTitle;dialogTitle.textContent=t.title;pages.innerHTML=`<section><small>01 · RESUMEN</small><h3>${t.date}</h3><p><b>Sede:</b> ${t.location}<br><b>Categorías:</b> ${t.categories}<br><b>Valor:</b> ${t.price}</p><button class="button button--blue enroll-button" type="button" data-register="${t.id}">Inscribir pareja ↗</button></section><section data-results-placeholder><small>02 · GRUPOS Y RESULTADOS</small><p>Los grupos y resultados se publicarán al cerrar las inscripciones.</p></section>`;dialog.showModal()});
document.querySelector('.dialog__close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});const toggle=document.querySelector('.theme-toggle');const saved=localStorage.getItem('theme');function setTheme(theme){document.documentElement.dataset.theme=theme;toggle.setAttribute('aria-pressed',String(theme==='dark'));toggle.setAttribute('aria-label',theme==='dark'?'Modo oscuro activo. Cambiar a modo claro':'Modo claro activo. Cambiar a modo oscuro');}setTheme(saved||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));toggle.addEventListener('click',()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('theme',n);setTheme(n)});
function registrationForm(t){const category=t.categoryOptions?.[0];return `<section class="registration-page"><div style="margin-bottom:14px;"><button type="button" class="button button--cancel button--small" data-back-to-tournament="${t.id}">← Volver al resumen</button></div><small>INSCRIPCIÓN POR PAREJA</small><h3>${t.title}</h3><p>${t.date}</p><form id="pair-registration" data-category-id="${category?.id||''}" data-category-name="${category?.name||''}" novalidate><div class="player-fields"><h4>Jugadora 1</h4><label>Nombre<input name="firstName" required></label><label>Apellido<input name="firstLastName" required></label><label>Alias<input name="firstAlias" required></label><label>DNI<input name="firstDni" type="number" inputmode="numeric" pattern="[0-9]+" required></label></div><div class="player-fields"><h4>Jugadora 2</h4><label>Nombre<input name="secondName" required></label><label>Apellido<input name="secondLastName" required></label><label>Alias<input name="secondAlias" required></label><label>DNI<input name="secondDni" type="number" inputmode="numeric" pattern="[0-9]+" required></label></div><label class="contact-field">Teléfono de contacto<input name="phone" type="tel" inputmode="numeric" pattern="[0-9]+" required></label><button class="button button--primary" type="submit">Enviar inscripción por WhatsApp ↗</button><p class="form-message" aria-live="polite"></p></form></section>`}
dialog.addEventListener('click',event=>{const back=event.target.closest('[data-back-to-tournament]');if(back){const card=document.querySelector(`[data-id="${back.dataset.backToTournament}"]`);if(card)card.click();return}const register=event.target.closest('[data-register]');if(register){const t=tournaments.find(item=>item.id===register.dataset.register);document.querySelector('.tournament-subnav')?.remove();pages.innerHTML=registrationForm(t);pages.dataset.tournament=t.id}});
dialog.addEventListener('submit',async event=>{if(event.target.id!=='pair-registration')return;event.preventDefault();const form=event.target;if(!form.checkValidity()){form.reportValidity();return}const categoryId=form.dataset.categoryId;if(!categoryId){form.querySelector('.form-message').textContent='Este torneo no tiene una categoría disponible.';return}const whatsappWindow=window.open('','_blank');const d=Object.fromEntries(new FormData(form));const t=tournaments.find(item=>item.id===pages.dataset.tournament);const message=form.querySelector('.form-message');const button=form.querySelector('button[type="submit"]');button.disabled=true;button.setAttribute('aria-busy','true');const norm=s=>String(s||'').trim().toLowerCase();const candKey=[norm(d.firstAlias),norm(d.secondAlias)].sort().join(' /// ');const {data:catPairs}=await supabaseClient.from('pairs').select('player_one_alias,player_two_alias').eq('category_id',categoryId);if((catPairs||[]).some(p=>[norm(p.player_one_alias),norm(p.player_two_alias)].sort().join(' /// ')===candKey)){whatsappWindow?.close();button.disabled=false;button.removeAttribute('aria-busy');message.textContent='Esta pareja ya se encuentra inscripta en este torneo.';return}const {error}=await supabaseClient.rpc('register_tournament_pair',{p_category_id:categoryId,p_player_one_first_name:d.firstName.trim(),p_player_one_last_name:d.firstLastName.trim(),p_player_one_alias:d.firstAlias.trim(),p_player_one_dni:d.firstDni,p_player_two_first_name:d.secondName.trim(),p_player_two_last_name:d.secondLastName.trim(),p_player_two_alias:d.secondAlias.trim(),p_player_two_dni:d.secondDni,p_contact_phone:d.phone});button.disabled=false;button.removeAttribute('aria-busy');if(error){whatsappWindow?.close();message.textContent=error.message||'No se pudo registrar la pareja. Reintentá.';return}const msg=`Hola, recibí una inscripción pendiente de confirmación.\n\nTorneo: ${t.title} · ${t.date}\nCategoría: ${form.dataset.categoryName}\n\nJugadora 1\nNombre: ${d.firstName} ${d.firstLastName}\nAlias: ${d.firstAlias}\nDNI: ${d.firstDni}\n\nJugadora 2\nNombre: ${d.secondName} ${d.secondLastName}\nAlias: ${d.secondAlias}\nDNI: ${d.secondDni}\n\nTeléfono de contacto: ${d.phone}\n\nLa pareja quedó pendiente de confirmación de pago.`;message.textContent='Inscripción recibida. Te llevamos a WhatsApp para avisar el pago.';const whatsappUrl=`https://wa.me/${t.contact}?text=${encodeURIComponent(msg)}`;if(whatsappWindow)whatsappWindow.location.href=whatsappUrl;else window.open(whatsappUrl,'_blank','noopener')});
async function loadPublicTournaments(){
  const {data,error}=await supabaseClient.from('tournaments').select('id,title,start_date,end_date,location,registration_price,status,whatsapp_number,tournament_categories(id,name)').neq('status','draft').order('start_date');
  if(error||!data?.length)return;
  tournaments=data.map(t=>({id:t.id,day:new Date(`${t.start_date}T12:00:00`).getDate(),month:new Intl.DateTimeFormat('es-AR',{month:'short'}).format(new Date(`${t.start_date}T12:00:00`)).replace('.','').toUpperCase(),year:new Date(`${t.start_date}T12:00:00`).getFullYear(),title:t.title,status:t.status==='open'?'Inscripciones abiertas':t.status==='in_progress'?'En curso':'Finalizado',location:t.location,price:t.registration_price?`$${Number(t.registration_price).toLocaleString('es-AR')} por persona`:'A confirmar',categories:(t.tournament_categories||[]).map(c=>c.name).join(' · ')||'A confirmar',categoryOptions:t.tournament_categories||[],date:`${formatCardDate(t.start_date)} - ${formatCardDate(t.end_date)}`,contact:t.whatsapp_number||'5492233122044',pairs:[]}));
  renderTournamentList();
}
loadPublicTournaments();
document.querySelector('.admin-access')?.addEventListener('click',()=>{window.location.href='admin.html'});
