const supabaseClient = window.supabase.createClient('https://scdgdfxkvkgqueeozznd.supabase.co', 'sb_publishable_UgQh8Fq2C-ydgDCPSbii6A_J5Eqoia1');
const sampleTournaments=[{id:'copa',day:'21',month:'AGO',year:'2026',title:'Copa Miramarense · 5ª Edición',status:'Inscripciones abiertas',location:'Club Náutico Miramar',price:'$30.000 por pareja',categories:'5ª y 6ª Femenino',date:'21/08 - 23/08',contact:'5492234977246',pairs:['Carolina Rossi / Mariela Gómez','Sofía Martínez / Luciana Díaz','Valeria Fernández / Andrea Ruiz']},{id:'primavera',day:'19',month:'SEP',year:'2026',title:'Abierto de Primavera',status:'Próximamente',location:'Complejo La Cancha',price:'A confirmar',categories:'Categorías mixtas',date:'19/09 - 20/09',contact:'5492234977246',pairs:[]}];
let tournaments=sampleTournaments;
const formatCardDate=value=>{const [year,month,day]=String(value||'').split('-');return month&&day?`${day}/${month}`:''};
const list=document.querySelector('#tournament-list'),dialog=document.querySelector('#tournament-dialog'),pages=document.querySelector('#detail-pages');
dialog.addEventListener('toggle',()=>document.body.classList.toggle('modal-open',dialog.open));
const tournamentGroup=t=>t.status==='En curso'?'current':t.status==='Finalizado'?'finished':'upcoming';
const tournamentCard=t=>`<article class="tournament-card"><button type="button" data-id="${t.id}" aria-label="Ver torneo: ${t.title}"><span class="tournament-card__top"><strong>${t.title} (${t.categories})</strong><span class="card-status ${tournamentGroup(t)==='upcoming'?'card-status--open':'card-status--started'}">${tournamentGroup(t)==='upcoming'?'Abierto':tournamentGroup(t)==='finished'?'Finalizado':'En curso'}</span></span><span class="tournament-card__meta">${t.location} · ${t.date.replace(' - ', ' al ')}</span></button></article>`;
const tournamentSection=(title,items)=>!items.length?'':`<section class="tournament-home-section"><h3>${title}</h3><div class="tournament-home-section__list">${items.map(tournamentCard).join('')}</div></section>`;
const renderTournamentList=()=>{const current=tournaments.filter(t=>tournamentGroup(t)==='current'),upcoming=tournaments.filter(t=>tournamentGroup(t)==='upcoming'),finished=tournaments.filter(t=>tournamentGroup(t)==='finished');list.innerHTML=`${tournamentSection('En curso',current)}${tournamentSection('Próximos torneos',upcoming)}${tournamentSection('Terminados',finished)}`||'<p class="tournament-list__empty">No hay torneos publicados por el momento.</p>'};
renderTournamentList();
list.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;const t=tournaments.find(x=>x.id===b.dataset.id);const dialogTitle=document.querySelector('#dialog-title');delete dialogTitle.dataset.baseTitle;dialogTitle.textContent=t.title;pages.innerHTML=`<section><small>01 · RESUMEN</small><h3>${t.date}</h3><p><b>Sede:</b> ${t.location}<br><b>Categorías:</b> ${t.categories}<br><b>Valor:</b> ${t.price}</p><button class="button button--primary enroll-button" type="button" data-register="${t.id}">Inscribir pareja ↗</button></section><section data-results-placeholder><small>02 · GRUPOS Y RESULTADOS</small><p>Los grupos y resultados se publicarán al cerrar las inscripciones.</p></section>`;dialog.showModal()});
document.querySelector('.dialog__close').addEventListener('click',()=>dialog.close());const toggle=document.querySelector('.theme-toggle');const saved=localStorage.getItem('theme');function setTheme(theme){document.documentElement.dataset.theme=theme;toggle.setAttribute('aria-pressed',String(theme==='dark'));toggle.setAttribute('aria-label',theme==='dark'?'Modo oscuro activo. Cambiar a modo claro':'Modo claro activo. Cambiar a modo oscuro');}setTheme(saved||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));toggle.addEventListener('click',()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('theme',n);setTheme(n)});
function registrationForm(t){return `<section class="registration-page"><small>INSCRIPCIÓN POR PAREJA</small><h3>${t.title}</h3><p>${t.date}</p><form id="pair-registration" novalidate><div class="player-fields"><h4>Jugadora 1</h4><label>Nombre<input name="firstName" required></label><label>Apellido<input name="firstLastName" required></label><label>Alias<input name="firstAlias" required></label><label>DNI<input name="firstDni" type="number" inputmode="numeric" pattern="[0-9]+" required></label><label>Categoría<input name="firstCategory" required></label></div><div class="player-fields"><h4>Jugadora 2</h4><label>Nombre<input name="secondName" required></label><label>Apellido<input name="secondLastName" required></label><label>Alias<input name="secondAlias" required></label><label>DNI<input name="secondDni" type="number" inputmode="numeric" pattern="[0-9]+" required></label><label>Categoría<input name="secondCategory" required></label></div><label class="contact-field">Teléfono de contacto<input name="phone" type="tel" inputmode="numeric" pattern="[0-9]+" required></label><button class="button button--primary" type="submit">Continuar a WhatsApp ↗</button></form></section>`}
dialog.addEventListener('click',event=>{const register=event.target.closest('[data-register]');if(register){const t=tournaments.find(item=>item.id===register.dataset.register);pages.innerHTML=registrationForm(t);pages.dataset.tournament=t.id}});
dialog.addEventListener('submit',event=>{if(event.target.id!=='pair-registration')return;event.preventDefault();const form=event.target;if(!form.checkValidity()){form.reportValidity();return}const d=Object.fromEntries(new FormData(form));const t=tournaments.find(item=>item.id===pages.dataset.tournament);const msg=`Hola, quiero inscribirme en: ${t.title} · ${t.date}\n\nJugadora 1\nNombre: ${d.firstName} ${d.firstLastName}\nAlias: ${d.firstAlias}\nDNI: ${d.firstDni}\nCategoría: ${d.firstCategory}\n\nJugadora 2\nNombre: ${d.secondName} ${d.secondLastName}\nAlias: ${d.secondAlias}\nDNI: ${d.secondDni}\nCategoría: ${d.secondCategory}\n\nTeléfono de contacto: ${d.phone}`;window.open(`https://wa.me/${t.contact}?text=${encodeURIComponent(msg)}`,'_blank','noopener')});
async function loadPublicTournaments(){
  const {data,error}=await supabaseClient.from('tournaments').select('id,title,start_date,end_date,location,registration_price,status,whatsapp_number,tournament_categories(name)').neq('status','draft').order('start_date');
  if(error||!data?.length)return;
  tournaments=data.map(t=>({id:t.id,day:new Date(`${t.start_date}T12:00:00`).getDate(),month:new Intl.DateTimeFormat('es-AR',{month:'short'}).format(new Date(`${t.start_date}T12:00:00`)).replace('.','').toUpperCase(),year:new Date(`${t.start_date}T12:00:00`).getFullYear(),title:t.title,status:t.status==='open'?'Inscripciones abiertas':t.status==='in_progress'?'En curso':'Finalizado',location:t.location,price:t.registration_price?`$${Number(t.registration_price).toLocaleString('es-AR')} por pareja`:'A confirmar',categories:(t.tournament_categories||[]).map(c=>c.name).join(' · ')||'A confirmar',date:`${formatCardDate(t.start_date)} - ${formatCardDate(t.end_date)}`,contact:t.whatsapp_number||'5492234977246',pairs:[]}));
  renderTournamentList();
}
loadPublicTournaments();
const adminDialog=document.querySelector('#admin-dialog');
const adminContent=document.querySelector('#admin-content');
document.querySelector('.admin-access').addEventListener('click',()=>{window.location.href='admin.html'});
document.querySelector('.admin-close').addEventListener('click',()=>adminDialog.close());
async function renderAdmin(){
 const {data:{user}}=await supabaseClient.auth.getUser();
 if(!user){adminContent.innerHTML=`<section class="admin-screen"><p class="kicker">ADMINISTRACIÓN</p><h2>Ingresar</h2><form id="admin-login"><label>Email<input type="email" name="email" required></label><label>Contraseña<input type="password" name="password" required></label><button class="button button--primary" type="submit">Ingresar</button><p class="admin-message"></p></form></section>`;return}
 const {data:admin}=await supabaseClient.from('admins').select('user_id').eq('user_id',user.id).maybeSingle();
 if(!admin){adminContent.innerHTML=`<section class="admin-screen"><p class="kicker">ACCESO DENEGADO</p><h2>Esta cuenta no es administradora.</h2><button class="button button--outline" id="admin-signout">Cerrar sesión</button></section>`;return}
 const {data:items}=await supabaseClient.from('tournaments').select('id,title,start_date,end_date,status,tournament_categories(name)').order('start_date');
 adminContent.innerHTML=`<section class="admin-screen"><div class="admin-screen__head"><div><p class="kicker">PANEL ADMIN</p><h2>Torneos</h2></div><button class="button button--outline" id="admin-signout">Salir</button></div><form id="tournament-form" class="admin-form"><label>Nombre del torneo<input name="title" required minlength="4"></label><label>Fecha de inicio<input name="startDate" type="date" required></label><label>Fecha de cierre<input name="endDate" type="date" required></label><label>Sede<input name="location" required></label><label>Precio por pareja<input name="price" type="number" min="0" step="1"></label><label>WhatsApp de inscripciones<input name="whatsapp" type="tel" inputmode="numeric" pattern="[0-9]+" required></label><label class="admin-form__wide">Categorías <small>Separalas con comas; podés escribir cualquier nombre.</small><input name="categories" placeholder="Ej.: 5ª Femenino, 6ª Femenino" required></label><label class="admin-form__wide">Descripción<textarea name="description" rows="3"></textarea></label><button class="button button--primary" type="submit">Crear torneo</button><p class="admin-message"></p></form><div class="admin-list"><h3>Torneos cargados</h3>${(items||[]).map(t=>`<article><div><b>${t.title}</b><span>${t.start_date} · ${(t.tournament_categories||[]).map(c=>c.name).join(', ')}</span></div><button type="button" data-delete-tournament="${t.id}">Eliminar</button></article>`).join('')||'<p>Aún no hay torneos.</p>'}</div></section>`;
}
adminDialog.addEventListener('submit',async event=>{event.preventDefault();const form=event.target;if(form.id==='admin-login'){const data=Object.fromEntries(new FormData(form));const {error}=await supabaseClient.auth.signInWithPassword({email:data.email,password:data.password});form.querySelector('.admin-message').textContent=error?'No se pudo iniciar sesión.': '';if(!error)await renderAdmin();return}if(form.id==='tournament-form'){const data=Object.fromEntries(new FormData(form));const message=form.querySelector('.admin-message');if(data.endDate<data.startDate){message.textContent='La fecha de cierre no puede ser anterior al inicio.';return}const {data:created,error}=await supabaseClient.from('tournaments').insert({title:data.title,start_date:data.startDate,end_date:data.endDate,location:data.location,registration_price:data.price||null,whatsapp_number:data.whatsapp,status:'open',description:data.description||''}).select('id').single();if(error){message.textContent='No se pudo crear el torneo.';return}const categories=String(data.categories).split(',').map(name=>name.trim()).filter(Boolean).map(name=>({tournament_id:created.id,name}));if(categories.length){const {error:categoryError}=await supabaseClient.from('tournament_categories').insert(categories);if(categoryError){message.textContent='Torneo creado, pero no se guardaron categorías.';return}}await renderAdmin();await loadPublicTournaments();}});
adminDialog.addEventListener('click',async event=>{if(event.target.id==='admin-signout'){await supabaseClient.auth.signOut();await renderAdmin();return}const button=event.target.closest('[data-delete-tournament]');if(button&&confirm('¿Eliminar este torneo y sus categorías?')){const {error}=await supabaseClient.from('tournaments').delete().eq('id',button.dataset.deleteTournament);if(!error){await renderAdmin();await loadPublicTournaments()}}});
